version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_ai
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgressql/data

volumes:
  .postgres-data:
